### ISSUE TITLE
Avis apres premier test

### ISSUE THREAD

**Issue by dracoeric** [malikbenkirane/42.automake#1]
Hello,

J'ai essayé de suivre le readme, que dois-je faire apres avoir utiliser la commande sh configure ? J'ai copier les fichiers directement dans mon clone de repo de j02.

Après avoir lancer make, j'ai le message : 
make: *** No rule to make target `ft_putchar.o', needed by `test'.  Stop.

merci, super boulot

**Comment by malikbenkirane** [comment]
C'est qu'il manque le fichier `ft_putchar.o` nécessaire pour tester les programmes.
Ce fichier contient la fonction `ft_putchar` (seule fonction autorisée et nécessaire dans les exercices du jour 2). Pour le fabriquer tu peux utiliser `deps/ft_putchar.c` disponible dans ce repo.
Avec quelque chose comme
```
gcc -o ft_putchar.o -c deps/ft_putchar.c
```
tu auras le fichier nécessaire pour compiler et tester les exercices.
La procédure sera à priori la même pour chaque fonction "autorisée".

Fais moi savoir si le problème est résolu.  Bon courage !

**Comment by dracoeric** [comment]
Okay, ca marche !

Il faut mettre le ft_putchar.o creer dans le dossier j02

**Comment by malikbenkirane** [comment]
Exact si il y a pas d'autres soucis je close l'issue. Bon courage !
